version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-50-17-255-120.compute-1.amazonaws.com
            port: '5432'
            database: d55326nafgo1ea
            ssl: true
            user: ryxnkytbbcpzxd
            password: cbc288f116f354af7c0f714dd190424fb0dc845c5dc3660574345ee8c414aa2a
            migrations: true
